package com.sl.dao;

import com.sl.domain.PayMntContact;
import com.sl.domain.PayMntContactExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PayMntContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int countByExample(PayMntContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int deleteByExample(PayMntContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int insert(PayMntContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int insertSelective(PayMntContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    List<PayMntContact> selectByExample(PayMntContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    PayMntContact selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int updateByExampleSelective(@Param("record") PayMntContact record, @Param("example") PayMntContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int updateByExample(@Param("record") PayMntContact record, @Param("example") PayMntContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int updateByPrimaryKeySelective(PayMntContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_mnt_contact
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    int updateByPrimaryKey(PayMntContact record);
}