package com.sl.domain;

import java.io.Serializable;
import java.util.Date;

public class PayMntContact implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.id
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.name
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.phone
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.email
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.remark
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.create_time
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.modifier
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_mnt_contact.modify_time
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.id
     *
     * @return the value of pay_mnt_contact.id
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.id
     *
     * @param id the value for pay_mnt_contact.id
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.name
     *
     * @return the value of pay_mnt_contact.name
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.name
     *
     * @param name the value for pay_mnt_contact.name
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.phone
     *
     * @return the value of pay_mnt_contact.phone
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.phone
     *
     * @param phone the value for pay_mnt_contact.phone
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.email
     *
     * @return the value of pay_mnt_contact.email
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.email
     *
     * @param email the value for pay_mnt_contact.email
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.remark
     *
     * @return the value of pay_mnt_contact.remark
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.remark
     *
     * @param remark the value for pay_mnt_contact.remark
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.create_time
     *
     * @return the value of pay_mnt_contact.create_time
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.create_time
     *
     * @param createTime the value for pay_mnt_contact.create_time
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.modifier
     *
     * @return the value of pay_mnt_contact.modifier
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.modifier
     *
     * @param modifier the value for pay_mnt_contact.modifier
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_mnt_contact.modify_time
     *
     * @return the value of pay_mnt_contact.modify_time
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_mnt_contact.modify_time
     *
     * @param modifyTime the value for pay_mnt_contact.modify_time
     *
     * @mbggenerated Thu Dec 26 12:36:29 GMT+08:00 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "PayMntContact{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", remark='" + remark + '\'' +
                ", createTime=" + createTime +
                ", modifier='" + modifier + '\'' +
                ", modifyTime=" + modifyTime +
                '}';
    }
}