package com.sl.domain;

import java.io.Serializable;
import java.util.Date;

public class PayMntType implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 4725957415800105955L;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.type_id
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private Integer typeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.type_name
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private String typeName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.service_intf
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private String serviceIntf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.type_category
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private Integer typeCategory;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.type_status
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private String typeStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.belong_sys
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private String belongSys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.create_time
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.modify_time
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private Date modifyTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.modify_person
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private String modifyPerson;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pay_mnt_type.remark
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    private String remark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.type_id
     *
     * @return the value of pay_mnt_type.type_id
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.type_id
     *
     * @param typeId the value for pay_mnt_type.type_id
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.type_name
     *
     * @return the value of pay_mnt_type.type_name
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.type_name
     *
     * @param typeName the value for pay_mnt_type.type_name
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.service_intf
     *
     * @return the value of pay_mnt_type.service_intf
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public String getServiceIntf() {
        return serviceIntf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.service_intf
     *
     * @param serviceIntf the value for pay_mnt_type.service_intf
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setServiceIntf(String serviceIntf) {
        this.serviceIntf = serviceIntf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.type_category
     *
     * @return the value of pay_mnt_type.type_category
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public Integer getTypeCategory() {
        return typeCategory;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.type_category
     *
     * @param typeCategory the value for pay_mnt_type.type_category
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setTypeCategory(Integer typeCategory) {
        this.typeCategory = typeCategory;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.type_status
     *
     * @return the value of pay_mnt_type.type_status
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public String getTypeStatus() {
        return typeStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.type_status
     *
     * @param typeStatus the value for pay_mnt_type.type_status
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setTypeStatus(String typeStatus) {
        this.typeStatus = typeStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.belong_sys
     *
     * @return the value of pay_mnt_type.belong_sys
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public String getBelongSys() {
        return belongSys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.belong_sys
     *
     * @param belongSys the value for pay_mnt_type.belong_sys
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setBelongSys(String belongSys) {
        this.belongSys = belongSys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.create_time
     *
     * @return the value of pay_mnt_type.create_time
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.create_time
     *
     * @param createTime the value for pay_mnt_type.create_time
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.modify_time
     *
     * @return the value of pay_mnt_type.modify_time
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.modify_time
     *
     * @param modifyTime the value for pay_mnt_type.modify_time
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.modify_person
     *
     * @return the value of pay_mnt_type.modify_person
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.modify_person
     *
     * @param modifyPerson the value for pay_mnt_type.modify_person
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pay_mnt_type.remark
     *
     * @return the value of pay_mnt_type.remark
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pay_mnt_type.remark
     *
     * @param remark the value for pay_mnt_type.remark
     *
     * @ibatorgenerated Tue Nov 19 11:45:21 GMT+08:00 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}